blog/urls.py
from django.urls import path
from .views import index

app_name = 'blogs'
urlpatterns = [
    path('',index,name="list"),

]

config/urls.py
from config import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include




urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('article.urls',namespace='articles')),
    path('blog/',include('blog.urls',namespace='blogs')),
    path('account/',include('account.urls',namespace='auth')),
    path('recipes/', include('recipes.urls', namespace='recipes')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path
from .views import recipe_list, recipe_detail, recipe_create, recipe_update, recipe_delete, tag_create, tag_detail, \
    tag_delete, tag_update, tag_list, ing_create, ing_update, ing_delete, my_recipes
app_name = 'recipes'


urlpatterns = [
    path('lists/', recipe_list, name='list'),
    path('my/lists/', my_recipes, name='my_list'),
    path('detail/<slug:slug>/', recipe_detail, name='recipe_detail'),
    path('create/', recipe_create, name='recipe_create'),
    path('update/<slug:slug>/', recipe_update, name='recipe_update'),
    path('delete/<slug:slug>/', recipe_delete, name='recipe_delete'),

    path('tag_list/', tag_list, name='tag_list'),
    path('tag/detail/<int:pk>/', tag_detail, name='tag_detail'),
    path('tag/create/', tag_create, name='tag_create'),
    path('tag/update/<int:pk>/', tag_update, name='tag_update'),
    path('tag/delete /<int:pk>/', tag_delete, name='tag_delete'),


    path('<slug:recipe_slug>/ing/create/', ing_create, name='ing_create'),
    path('<slug:recipe_slug>/ing/update/<int:pk>/', ing_update, name='ing_update'),
    path('<slug:recipe_slug>/ing/delete/<int:pk>/', ing_delete, name='ing_delete'),
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.utils.text import slugify
import random
import string
# Create your models here.


class Tag(models.Model):
    title = models.CharField(max_length=221)

    def __str__(self):
        return self.title


class Recipe(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=221, db_index=True)
    slug = models.SlugField(null=True, unique=True)
    is_active = models.BooleanField(default=True)
    modified_date = models.DateTimeField(auto_now=True)
    created_date = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title


class RecipeIngredient(models.Model):
    UNIT = (
        (0, "GRAMM"),
        (1, "MilliLITR"),
        (3, "DONA"),

    )
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='ingredients')
    title = models.CharField(max_length=221)
    quantity = models.IntegerField()
    unit = models.IntegerField(choices=UNIT)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    # def get_author(self):
    #     return self.recipe.author


def recipe_post_save(sender, instance, created, *args, **kwargs):
    if created:
        if instance.slug is None:
            instance.slug = slugify(instance.title)
            try:
                instance.save()
            except Exception as e:
                rand = "".join(random.choice(string.ascii_lowercase) for _ in range(4))
                instance.slug = slugify(instance.title) + f"-{rand}"
                instance.save()


post_save.connect(recipe_post_save, sender=Recipe)

recipes/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Recipe, Tag, RecipeIngredient


class RecipeCreateForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['id', 'author', 'title', 'is_active', 'tags']
        exclude = ['author', 'is_active']

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) < 5:
            raise ValidationError("title 10 ta belgidan koproq bo'lishi kerak")
        if not title.istitle():
            raise ValidationError("Bosh harf bilan yozilishi kerak")
        return title

    def __init__(self, *args, **kwargs):
        super(RecipeCreateForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Recipe...'
        })
        self.fields['tags'].widget.attrs.update({
            'class': 'form-control tags'
        })


class RecipeUpdateForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['id', 'author', 'title', 'is_active', 'tags']
        exclude = ['author', ]

    def __init__(self, *args, **kwargs):
        super(RecipeUpdateForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Recipe...'
        })
        self.fields['tags'].widget.attrs.update({
            'class': 'form-control tags'
        })


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(TagForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Tags...'
        })


class RecipeIngredientForm(forms.ModelForm):
    class Meta:
        model = RecipeIngredient
        fields = '__all__'
        exclude = ['recipe', ]

    def __init__(self, *args, **kwargs):
        super(RecipeIngredientForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Recipes...'
        })
        self.fields['quantity'].widget.attrs.update({
            'class': 'form-control',
        })
        self.fields['unit'].widget.attrs.update({
            'class': 'form-control',
        })

recipes/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from .models import RecipeIngredient, Recipe, Tag
from .forms import RecipeCreateForm, RecipeUpdateForm, TagForm, RecipeIngredientForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponse

# Create your views here.

# recipes ------------------------------------------------------------


def recipe_list(request):
    recipes = Recipe.objects.filter(is_active=True).order_by('-id')
    tags_list = Tag.objects.all()
    tag = request.GET.get('tag')
    q = request.GET.get('q')
    if q:
        recipes = recipes.filter(title__icontains=q)
    if tag:
        recipes = recipes.filter(tags__title=tag).distinct()
    ctx = {
        'object_list': recipes,
        'tags_list': tags_list,

    }
    return render(request, 'recipe/list.html', ctx)


def recipe_detail(request, slug):

    recipe = get_object_or_404(Recipe, slug=slug)
    # recipe=Recipe.objects.get(slug=slug)
    ctx = {
        'object': recipe
    }
    return render(request, 'recipe/detail.html', ctx)

@login_required
def recipe_create(request, *args, **kwargs):
    form = RecipeCreateForm()
    if request.method == "POST":
        form = RecipeCreateForm(request.POST or None)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.author = request.user
            obj.is_active = True
            obj.save()
            form.save_m2m()
            return redirect(f'/recipes/detail/{obj.slug}/')
    ctx = {
        'form': form
    }
    return render(request, 'recipe/create.html', ctx)



@login_required
def recipe_update(request, slug):
    obj = get_object_or_404(Recipe,slug=slug)
    if request.user != obj.author:
        return HttpResponse("<h1>Bu sizga tegishli emas(451)</h1>")
    form = RecipeUpdateForm(instance=obj)
    if request.method == "POST":
        form = RecipeUpdateForm(data=request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return redirect(reverse('recipes:recipe_detail', kwargs={"slug": obj.slug}))
    ctx = {
        'form': form
    }
    return render(request, 'recipe/update.html', ctx)

@login_required
def recipe_delete(request, slug):
    obj = get_object_or_404(Recipe, slug=slug)
    if request.user != obj.author:
        if not request.user.is_superuser:
            return HttpResponse("<h1>Bu sizga tegishli emas(451)</h1>")
    if request.method == 'POST':
        obj.delete()
        messages.error(request,  f"<b>{obj.title}</b> o'chirlidi")
        return redirect('recipes:list')
    ctx = {
        'object': obj
    }
    return render(request, 'recipe/delete.html', ctx)


# my recipes------------------------------------------------------------------------------
@login_required
def my_recipes(request):
    user = request.user
    recipes = Recipe.objects.filter(author=user)
    tags_list = Tag.objects.all()
    ctx = {
        'object_list': recipes,
        'tags_list': tags_list
    }
    return render(request, 'recipe/list.html', ctx)


# tags ------------------------------------------------------------


def tag_list(request):
    tags = Tag.objects.order_by('-id')
    ctx = {
        'object_list': tags
    }
    return render(request, 'recipe/tag/list.html', ctx)


@login_required
def tag_create(request, *args, **kwargs):
    form = TagForm()
    if request.method == "POST":
        form = TagForm(request.POST or None)
        if form.is_valid():
            obj = form.save()

            return redirect(reverse('recipes:tag_detail', kwargs={"pk": obj.id}))
    ctx = {
        'form': form
    }
    return render(request, 'recipe/tag/create.html', ctx)

def tag_detail(request, pk):
    tag = get_object_or_404(Tag, id=pk)
    ctx = {
        'object': tag
    }
    return render(request, 'recipe/tag/detail.html', ctx)


@login_required
def tag_update(request, pk):
    obj = get_object_or_404(Tag, id=pk)
    form = TagForm(instance=obj)
    if request.method == "POST":
        form = TagForm(data=request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return redirect(reverse('recipes:tag_detail', kwargs={"pk": obj.id}))
    ctx = {
        'form': form
    }
    return render(request, 'recipe/tag/update.html', ctx)

@login_required
def tag_delete(request, pk):
    obj = get_object_or_404(Tag, id=pk)
    if request.method == 'POST':
        obj.delete()
        messages.error(request,  f"<b>{obj.title}</b> ochirlidi")
        return redirect('recipes:tag_list')
    ctx = {
        'object': obj
    }
    return render(request, 'recipe/tag/delete.html', ctx)


# ingredients -----------------------------------------------------------------

@login_required
def ing_create(request, recipe_slug, *args, **kwargs):
    form = RecipeIngredientForm()
    recipe = get_object_or_404(Recipe, slug=recipe_slug)
    if request.user != recipe.author and not request.user.is_superuser:
        return HttpResponse("<h1>Bu sizga tegishli emas(451)</h1>")
    if request.method == "POST":
        form = RecipeIngredientForm(request.POST or None)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.recipe = recipe
            obj.save()
            return redirect(reverse('recipes:recipe_detail', kwargs={"slug": recipe.slug}))
    ctx = {
        'form': form,
    }
    return render(request, 'recipe/ing/create.html', ctx)



@login_required
def ing_update(request, recipe_slug, pk):
    obj = get_object_or_404(RecipeIngredient, id=pk)
    form = RecipeIngredientForm(instance=obj)
    recipe = get_object_or_404(Recipe, slug=recipe_slug)
    if request.method == "POST":
        form = RecipeIngredientForm(data=request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return redirect(reverse('recipes:recipe_detail', kwargs={"slug": recipe.slug}))
    ctx = {
        'form': form
    }
    return render(request,'recipe/ing/update.html', ctx)

@login_required
def ing_delete(request, recipe_slug, pk):
    obj = get_object_or_404(RecipeIngredient, id=pk)
    recipe = get_object_or_404(Recipe, slug=recipe_slug)
    if request.method == 'POST':
        obj.delete()
        messages.error(request,  f"<b>{obj.title}</b> ochirlidi")
        return redirect(reverse('recipes:recipe_detail', kwargs={"slug": recipe.slug}))
    ctx = {
        'object': obj
    }
    return render(request, 'recipe/ing/delete.html', ctx)

templates/recipe/create.html
{% extends 'base.html' %}


{% block title %}Recipe Creation{% endblock %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Title</label>
                        <span class="text-danger">{{ form.title.errors }}</span>
                        {{ form.title }}
                    </div>
                    <!--  <div class="mb-3">-->
                    <!--    <label for="exampleInputPassword1" class="form-label">Author</label>-->
                    <!--    {{ form.author }}-->
                    <!--  </div>-->
                    <div class="mb-3 form-check">
                        <label class="form-check-label" for="exampleCheck1">Tags</label>
                        {{ form.tags }}
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>




{% endblock %}

templates/recipe/delete.html
{% extends 'base.html' %}

{% block title %}Recipe Delete{% endblock %}

{% block content %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            <div class="card">
                <div class="card-body color-danger">
                    Siz rostanham <strong>{{ object.title }}</strong>ni ochirmoqchimisiz
                </div>
            </div>
            <div class="button-group mt-3">
                <a href="{% url 'recipes:recipe_detail' object.slug %}" class="btn btn-secondary">Yoq</a>
                <button type="submit" class="btn btn-danger">Ha</button>
            </div>
        </form>

    </div>




{% endblock %}

templates/recipe/detail.html
{% extends 'base.html' %}

{% block title %}Recipe Detail{% endblock %}

{% block content %}
    <div class="button-group"></div>
    <a href="{% url 'recipes:list' %}" class="btn-btn-link">back to recipe list</a>
    <a href="{% url 'recipes:ing_create' object.slug %}" class="btn btn-link {% if request.user != object.author and not request.user.is_superuser %}disabled{% endif %}">Add Ingredient</a>

    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{ object.title }}</h5>
            <p class="card-text">{{ object.author }}</p>
            <div class="button">
                {% for tag in object.tags.all %}
                    <a href="#" type="button" class="btn btn-outline-dark btn-sm">{{ tag.title }}</a>
                {% endfor %}
            </div>
            {% if request.user ==  object.author %}
                <a href="{% url 'recipes:recipe_update' object.slug %}" class="btn btn-light {% if request.user != object.author %}disabled{% endif %}">Edit</a>
                <a href="{% url 'recipes:recipe_delete' object.slug %}" class="btn btn-danger {% if request.user != object.author and not request.user.is_superuser %}disabled{% endif %}">Delete</a>
            {% endif %}
        </div>
        <div class="card-footer text-muted">
            {{ object.created_date }}
        </div>
    </div>


    <div class="row mt-4">
        {% for ingredient in object.ingredients.all %}
            <div class="col-sm-6 mb-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ ingredient.title }}</h5>
                        <p class="card-text">{{ ingredient.quantity }} - {{ ingredient.get_unit_display.lower }}</p>
                        {% if request.user == object.author %}
                        <a href="{% url 'recipes:ing_update' ingredient.recipe.slug ingredient.id %}"
                           class="btn btn-light">Edit</a>
                        <a href="{% url 'recipes:ing_delete'  ingredient.recipe.slug ingredient.id %}"
                           class="btn btn-danger">Delete</a>
                        {% endif %}
                    </div>
                    <div class="card-footer text-muted">
                        {{ ingredient.created_date }}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/recipe/list.html
{% extends 'base.html' %}

{% block title %}Recipe list {% endblock %}

{% block content %}
    <div class="button-group ">
        <a href="{% url 'recipes:my_list' %}" class="btn btn-light">My recipes</a>
        <a href="{% url 'recipes:recipe_create' %}" class="btn btn-link">Add new Recipe list</a>
        <a href="{% url 'recipes:tag_create' %}" class="btn btn-link">Add new Tag list</a>
    </div>
    <div class="search-div mt-3">
        <form action="{% url 'recipes:list' %}" class="search-form">
            <div class="row g-3 align-items-center">
                <div class="col-auto">
                    <input type="search" autocomplete="off" class="form-control" id="exampleFormControlInput2"
                           placeholder="search.." name="q">
                </div>
                <div class="col-auto">
                    <button type="submit" class="btn btn-primary">Search</button>
                </div>
            </div>
        </form>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <ol class="list-group list-group-numbered mt-3">
                    {% for object in object_list %}
                        <li class="list-group-item d-flex justify-content-between align-items-start">
                            <div class="ms-2 me-auto">
                                <div class="fm-bold">
                                    <a class="{% if not object.is_active %}bg-danger{% endif %}"
                                       href="{% url 'recipes:recipe_detail' object.slug %}">{{ object.title }}</a>
                                </div>
                                {{ object.author }}
                            </div>
                            <span class="badge bg-primary rounded-pill">{{ object.ingredient.count }}</span>
                        </li>
                    {% endfor %}
                </ol>
            </div>
            <div class="col-md-3">
                <div class="button-group">
                <a href="?tag=" class="btn btn-outline-dark btn-sm m-1">Hammasi</a>
                    {% for tag in tags_list %}
                        <a href="?tag={{ tag.title }}" class="btn btn-outline-dark btn-sm m-1">{{ tag.title }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>




{% endblock %}

templates/recipe/update.html
{% extends 'base.html' %}


{% block title %}Recipe Update{% endblock %}


{% block content %}
    <form method="post">
        {% csrf_token %}

        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Title</label>
            {{ form.title }}
        </div>
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Is_active</label>
            {{ form.is_active }}
        </div>

        <!--  <div class="mb-3">-->
        <!--    <label for="exampleInputPassword1" class="form-label">Author</label>-->
        <!--    {{ form.author }}-->
        <!--  </div>-->
        <div class="mb-3 form-check">
            <label class="form-check-label" for="exampleCheck1">Tags</label>
            {{ form.tags }}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

{% endblock %}