account/urls.py
from django.urls import path
from .views import login_view,logout_view,register_view

app_name = 'auth'


urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register')

]

blog/urls.py
from django.urls import path
from .views import index

app_name = 'blogs'
urlpatterns = [
    path('',index,name="list"),

]

config/urls.py
from config import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include




urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('article.urls',namespace='articles')),
    path('blog/',include('blog.urls',namespace='blogs')),
    path('account/',include('account.urls',namespace='auth')),
    path('recipes/', include('recipes.urls', namespace='recipes')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path
from .views import recipe_list, recipe_detail, recipe_create, recipe_update, recipe_delete, tag_create, tag_detail, \
    tag_delete, tag_update, tag_list, ing_create, ing_update, ing_delete, my_recipes
app_name = 'recipes'


urlpatterns = [
    path('lists/', recipe_list, name='list'),
    path('my/lists/', my_recipes, name='my_list'),
    path('detail/<slug:slug>/', recipe_detail, name='recipe_detail'),
    path('create/', recipe_create, name='recipe_create'),
    path('update/<slug:slug>/', recipe_update, name='recipe_update'),
    path('delete/<slug:slug>/', recipe_delete, name='recipe_delete'),

    path('tag_list/', tag_list, name='tag_list'),
    path('tag/detail/<int:pk>/', tag_detail, name='tag_detail'),
    path('tag/create/', tag_create, name='tag_create'),
    path('tag/update/<int:pk>/', tag_update, name='tag_update'),
    path('tag/delete /<int:pk>/', tag_delete, name='tag_delete'),


    path('<slug:recipe_slug>/ing/create/', ing_create, name='ing_create'),
    path('<slug:recipe_slug>/ing/update/<int:pk>/', ing_update, name='ing_update'),
    path('<slug:recipe_slug>/ing/delete/<int:pk>/', ing_delete, name='ing_delete'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}TRY Django{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>
<!--<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">-->
<body>
{% include 'nav.html' %}

<div>
    {% for message in messages %}
        {% if message.tags == "success" %}
            <div class="alert alert-success" role="alert">
                {{ message|safe }}
            </div>
        {% endif %}
        {% if message.tags == "error" %}
            <div class="alert alert-danger" role="alert">
                {{ message|safe }}
            </div>
        {% endif %}
        {% if message.tags == "info" %}
            <div class="alert alert-info" role="alert">
                {{ message|safe }}
            </div>
        {% endif %}
        {% if message.tags == "warning" %}
            <div class="alert alert-warning" role="alert">
                {{ message|safe }}
            </div>
        {% endif %}
    {% endfor %}
</div>
<div class="container pt-3 mt-0 ">
    {% block content %}

    {% endblock %}
</div>
{% include 'footer.html' %}
<!--<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>-->
<!--<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>-->
<!--<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>-->
<!--<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>-->
<script src="https://code.jquery.com/jquery-3.6.2.js" integrity="sha256-pkn2CUZmheSeyssYw3vMp1+xyub4m+e+QK4sQskvuo4="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

<hr>
</body>
</html>

templates/footer.html
{% load static %}

<div>
    <table>
        <tr>
             <a class="navbar-brand">
                <img src="{% static 'image/telegram.jpg' %}" alt="">
            <h1><a href="https://t.me/Muhammad_Rauf404">Telegram</a> </h1>
    </a>
        </tr>
        <tr>
             <a class="navbar-brand">
                <img src="{% static 'image/instagram.png' %}" alt="">
                <h1><a href="https://www.instagram.com/python_beckend_dev/">Instagram</a></h1>
    </a>
        </tr>
        <tr>
                <a class="navbar-brand">
                <img src="{% static 'image/github.png' %}" alt="">
                <h1><a href="https://github.com/seferonxkiller">GitHub</a></h1>
    </a>
        </tr>
    </table>
<!--    <a class="navbar-brand">-->
<!--                <img src="{% static 'image/telegram.jpg' %}" alt="">-->
<!--            <h1><a href="https://t.me/Muhammad_Rauf404">Telegram</a> </h1>-->
<!--    </a>-->
<!--    <a class="navbar-brand">-->
<!--                <img src="{% static 'image/instagram.png' %}" alt="">-->
<!--                <h1><a href="https://www.instagram.com/python_beckend_dev/">Instagram</a></h1>-->
<!--    </a>-->
<!--    <a class="navbar-brand">-->
<!--                <img src="{% static 'image/github.png' %}" alt="">-->
<!--                <h1><a href="https://github.com/seferonxkiller">GitHub</a></h1>-->
<!--    </a>-->
</div>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a href="{% url 'articles:list' %}">
            <img src="{% static 'image/img.png' %}" alt="">
        </a>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" href="{% url 'articles:list' %}">Article</a>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Recipes
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'recipes:list' %}">Recipes</a></li>
                        <li><a class="dropdown-item" href="{% url 'recipes:tag_list' %}">Tags</a></li>
                    </ul>
                </li>
                <a class="nav-link" href="{% url 'blogs:list' %}">Blogs</a>
            </div>
        </div>
        <div class="profile">
            {% if request.user.is_authenticated %}
                <span>{{ request.user }}</span>
                <span><a href="{% url 'auth:logout' %}"><button class="btn btn-primary">Logout</button></a></span>
            {% else %}
                <span><a href="{% url 'auth:login' %}"><button class="btn btn-primary">Login</button></a></span>
            {% endif %}
        </div>
    </div>
</nav>