article/urls.py
from django.urls import path
from .views import *

app_name = 'article'
urlpatterns = [
    path('',index, name="list"),
    path('article/detail/<slug:slug>/',detail,name="detail"),
    path('article/create/',create,name="create"),
    path('article/edit/<slug:slug>/',edit,name="edit"),
    path('article/delete/<slug:slug>/',delete,name="delete")

]

blog/urls.py
from django.urls import path
from .views import index

app_name = 'blogs'
urlpatterns = [
    path('',index,name="list"),

]

config/urls.py
from config import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include




urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('article.urls',namespace='articles')),
    path('blog/',include('blog.urls',namespace='blogs')),
    path('account/',include('account.urls',namespace='auth')),
    path('recipes/', include('recipes.urls', namespace='recipes')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

article/models.py
import string

from django.db import models
from django.utils.text import slugify
import random
from django.db.models.signals import post_save, pre_save
# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=221, db_index=True)
    slug = models.SlugField(unique=True, null=True, blank=True)
    image = models.ImageField(upload_to='article', null=True, blank=True)
    content = models.TextField(blank=True, null=True)
    is_deleted = models.BooleanField(default=False)
    modified_date = models.DateTimeField(auto_now=True,null=True)
    created_date = models.DateTimeField(auto_now_add=True, null=True)


    def __str__(self):
        return f" {self.title}  ({self.id})"
    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        super().save()
    # def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
    #     if self.slug is None:
    #         self.slug = slugify(self.title)
    #     try:
    #         super().save()
    #     except Exception as e:
    #         rand = "".join(random.choice(string.ascii_lowercase) for _ in range(4))
    #         self.slug = slugify(self.title) + f"-{rand}"
    #         super().save()

# def article_pre_save(sender, instance, *args, **kwargs):
#     # if instance.slug is None:
#         instance.slug = slugify(instance.title)
# def article_post_save(sender, instance, created, *args, **kwargs):
#     if created:
#         instance.slug = slugify(instance.title)
#         instance.save()



# pre_save.connect(article_pre_save, sender=Article)
# post_save.connect(article_post_save, sender=Article)

article/forms.py
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'image', 'content']

article/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, HttpResponse, Http404, redirect, reverse
from .models import Article
import random
from .forms import ArticleForm

def _index(request):
    _id = random.randint(1, 4)
    obj = Article.objects.get(id=_id)

    title = obj.content
    content = obj.content
    HTML_CONTENT = f"""
    <h1>{title} (id: {obj.id})</h1>
    <p>{content}</p1>
"""
    return HttpResponse(HTML_CONTENT)




def index(request):
    articles = Article.objects.filter(is_deleted__exact=False).order_by('-id')
    q = request.GET.get('q')
    if q:
        articles = articles.filter(title__icontains=q)
    return render(request,'article/index.html',{'object_list': articles})


def detail(request,slug=None):
    context = {}
    if slug:
        article = Article.objects.get(slug=slug)
        context['object'] = article
        return render(request,'article/detail.html', context)
    return Http404


def _create(request):
    context = {
        "created": False
    }
    if request.method == "POST":
        title =  request.POST.get('title')
        content = request.POST.get('content')
        article = Article.objects.create(titlle=title,content=content)
        context['object'] = article
        context['created'] = True
        # return redirect(reverse('articles:detail',kwargs={"pk": article.id}))
    return render(request,'article/create.html',context)




def create(request):
    form = ArticleForm(request.POST or None, files=request.FILES)
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        messages.success(request, f"Muvaffaqiyatli yangi xabar qoshdingiz")

        if form.is_valid():
            form.save()
            return redirect('article:list')
    context = {
        'form': form
    }

    return render(request, 'article/create.html', context)


@login_required(login_url='/auth/login/')
def edit(request, slug):
        article = Article.objects.get(slug=slug)
        form = ArticleForm(instance=article)
        if request.method == 'POST':
            form = ArticleForm(data=request.POST, instance=article, files=request.FILES)
            form.save()
            messages.success(request, "Muvaffaqiyatli xabarni yangiladingiz ")
            return redirect(reverse('article:detail', kwargs={"slug": article.slug}))
        ctx = {
            'form': form

        }
        return render(request,'article/edit.html',ctx)

@login_required(login_url='/auth/login/')
def delete(request, slug):
    article = Article.objects.get(slug=slug)
    if request.method == "POST":
        article.is_deleted =True
        article.save()
        messages.error(request, f"Article ochirildi({article.id})")
        # article.delete()
        return redirect('article:list')
    context = {
        'object': article
    }
    return render(request, 'article/delete.html',context)

templates/article/create.html
{%extends 'base.html'%}

{%block title%} Add new article {%endblock%}

{%block content%}

<form method="post">
    {%csrf_token%}
         <div class="mb-3">
            <label for="title" class="form-label">Title</label>
            <input type="text" class="form-control" id="title" name="title" placeholder="title">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">Content</label>
            <textarea class="form-control" id="content" name="content" rows="3"></textarea>
        </div>
     <div class="mb-3 form-check">
        <input type="checkbox" class="form-check-input" id="exampleCheck1">
        <label class="form-check-label" for="exampleCheck1">Check me out</label>
     </div>

        <div>
            <button type="submit" class="btn btn-primary">Add new</button>
        </div>
</form>

{%endblock%}

templates/article/delete.html
{% extends 'base.html' %}

{% block title %} Delete article{% endblock %}

{% block content %}
  <form method="post">
  {% csrf_token %}
  <p>
    Rostdan ham siz {{ object.title }} ni o'chirmoqchimisiz?
  </p>
  <a class="btn btn-secondary" href=" {% url 'article:list' %}">Yoq</a>
  <button type="submit" class="btn btn-danger">Ha</button>
</form>
{%  endblock %}

templates/article/detail.html
{%extends 'base.html'%}

{% block title %}{{object.title}}{% endblock %}

{% block content %}
    <h1>{{object.title}}</h1>
{% if object.image %}
    <div>
        <img src="{{ object.image.url }}" alt="">
    </div>
{% endif %}
    <p>{{object.content}}</p>
    <div>
        <code>{{ object.created_date}}</code>
    </div>
    <div>
        <span>last edited: <i> {{ object.modifield_data}}</i>></span>
    </div>
    <div>
        <a class="btn btn-primary" href="{% url 'article:edit' object.slug %}">
            Edit
        </a>
        <a class="btn btn-danger" href="{% url 'article:delete' object.slug %}">
            Delete
        </a>
    </div>
{% endblock %}

templates/article/edit article.html
{% extends 'base.html' %}


<form>
  <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label">Title</label>
    <input type="submit" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">We'll never share your title with anyone else.</div>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Content</label>
    <input type="submit" class="form-control" id="exampleInputPassword1">
  </div>
  <div class="mb-3 form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Edit</button>
</form>

templates/article/edit.html
{% extends 'base.html'%}

{%block title%} Edit {%endblock%}

{%block content%}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="mb-3">
            <label for="title" class="form-label">Title</label>
            <input type="text" class="form-control" id="title" name="title" placeholder="title">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">Content</label>
            <textarea class="form-control" id="content" name="content" rows="3"></textarea>
        </div>
     <div class="mb-3 form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>

        <div>
            <button type="submit" class="btn btn-primary">Edit</button>
        </div>
</form>


    <div>
<!--        <button type="submit">Edit</button>-->
<!--        <button class="btn btn-secondary"  type="submit">Edit</button>-->
<!--        <button class="btn btn-primary" type="submit">-->
<!--            Edit-->
<!--        </button>-->

    </div>

</form>
{% endblock %}

templates/article/index.html
{% extends 'base.html' %}

{% block title %}Articles{% endblock %}



{% block content %}
    <p>
        <a class="btn btn-link" href="{% url 'article:create' %}">add new adress</a>
    </p>

    <div class="search-div">
        <form class="search-form p-3" action="{% url 'article:list' %}">
            <div>
                <div class="row g-3 align-items-center">
                    <div class="col-auto">
                        <label for="exampleFormControlInput1" class="form-label">Search</label>
                    </div>
                    <div class="col-auto">
                        <input name="q" autocomplete="off" type="search" class="form-control"
                               id="exampleFormControlInput1"
                               placeholder="search....">
                    </div>
                    <div class="col-auto">
                        <button type="submit" class="btn btn-primary">Search</button>

                    </div>
                </div>
            </div>
        </form>
    </div>
    <div>
        <ol class="article_list">
            {% for object in object_list %}
                <li>
                    <a href="{% url 'article:detail' object.slug %}">{{ object.title }} ({{ object.id }})</a>
                    <a href="{% url 'article:edit' object.slug %}">Edit</a>
                    <a href="{% url 'article:delete' object.slug %}" style="color: red">Delete</a>
                </li>
            {% endfor %}
        </ol>
    </div>
{% endblock %}